"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
const input="glass-input w-full rounded-2xl border border-white/10 bg-slate-950/40 px-4 py-3 text-white shadow-inner shadow-black/10 outline-none transition placeholder:text-slate-600 focus:border-indigo-400/60 focus:ring-2 focus:ring-indigo-500/20";
export default function DeveloperProfilePage(){
 const supabase=useMemo(()=>createClient(),[]),[userId,setUserId]=useState<string|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState<string|null>(null);
 const [form,setForm]=useState({display_name:"",bio:"",website_url:"",github_url:"",gitlab_url:"",avatar_url:""});
 useEffect(()=>{void(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}setUserId(user.id);const {data}=await supabase.from("luma_developer_profiles").select("display_name,bio,website_url,github_url,gitlab_url,avatar_url").eq("developer_id",user.id).maybeSingle();if(data)setForm({display_name:data.display_name||"",bio:data.bio||"",website_url:data.website_url||"",github_url:data.github_url||"",gitlab_url:data.gitlab_url||"",avatar_url:data.avatar_url||""});setLoading(false)})()},[supabase]);
 const set=(k:keyof typeof form,v:string)=>setForm(x=>({...x,[k]:v}));
 async function save(e:React.FormEvent){e.preventDefault();if(!userId)return;setSaving(true);const clean=(v:string)=>v.trim()||null;const {error}=await supabase.from("luma_developer_profiles").upsert({developer_id:userId,display_name:clean(form.display_name),bio:clean(form.bio),website_url:clean(form.website_url),github_url:clean(form.github_url),gitlab_url:clean(form.gitlab_url),avatar_url:clean(form.avatar_url),updated_at:new Date().toISOString()},{onConflict:"developer_id"});setMessage(error?error.message:"Developer profile saved.");setSaving(false)}
 if(loading)return <div className="glass-page mx-auto max-w-3xl space-y-5 px-3 pb-20 sm:px-4"><div className="h-8 w-56 animate-pulse rounded bg-slate-800/70"/><div className="space-y-5 glass-panel p-6">{[0,1,2,3].map(i=><div key={i}><div className="mb-2 h-4 w-24 animate-pulse rounded bg-slate-800/60"/><div className="h-12 animate-pulse rounded-2xl bg-slate-800/40"/></div>)}</div></div>;
 if(!userId)return <div className="glass-page mx-auto max-w-3xl p-8 text-slate-300">Sign in to manage your developer profile.</div>;
 return <div className="glass-page mx-auto max-w-3xl space-y-6 px-3 pb-20 sm:px-4"><div><Link href="/dashboard" className="text-sm text-indigo-300">← Dashboard</Link><div className="glass-panel mt-4 p-5 sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center">{form.avatar_url?<img src={form.avatar_url} alt="" className="h-20 w-20 rounded-3xl border border-white/10 object-cover"/>:<div className="flex h-20 w-20 items-center justify-center rounded-3xl border border-white/10 bg-white/5 text-2xl font-bold text-indigo-200">{(form.display_name||"D").slice(0,1).toUpperCase()}</div>}<div><p className="ui-eyebrow">Public identity</p><h1 className="mt-1 text-3xl font-bold text-white">Developer profile</h1><p className="mt-2 text-sm leading-6 text-slate-400">Public information shown on your Luma Store developer page. Verification is managed by Luma Store.</p></div></div></div></div>{message&&<div role="status" className="rounded-2xl border border-indigo-400/20 bg-indigo-500/10 p-4 text-sm text-indigo-100">{message}</div>}<form onSubmit={save} className="space-y-5 glass-panel p-5 sm:p-6">
 {([["display_name","Display name"],["avatar_url","Avatar URL"],["website_url","Website"],["github_url","GitHub"],["gitlab_url","GitLab"]] as const).map(([k,l])=><div key={k}><label className="mb-2 block text-sm text-slate-300">{l}</label><input value={form[k]} onChange={e=>set(k,e.target.value)} className={input}/></div>)}
 <div><label className="mb-2 block text-sm text-slate-300">Bio</label><textarea rows={5} value={form.bio} onChange={e=>set("bio",e.target.value)} className={input}/></div>
 <div className="flex flex-col-reverse gap-3 border-t border-white/10 pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs leading-5 text-slate-500">Changes become visible on your public developer page after saving.</p><button disabled={saving} className="min-h-11 rounded-xl bg-indigo-500 px-5 py-2.5 font-semibold text-white shadow-lg shadow-indigo-950/20 transition hover:bg-indigo-400 disabled:cursor-not-allowed disabled:opacity-50">{saving?"Saving…":"Save profile"}</button></div>
 </form></div>
}