"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type AppStat={id:string;name:string|null;package_name:string|null;downloads:number};type PlatformStat={platform:string;downloads:number};type AppPlatformStat={app_id:string;name:string|null;package_name:string|null;platform:string;downloads:number};type DailyStat={download_day:string;app_id:string;platform:string;downloads:number};type FundingStat={provider:string;clicks:number};type Analytics={total_downloads:number;apps:AppStat[];platforms:PlatformStat[];app_platforms:AppPlatformStat[];daily:DailyStat[];funding:FundingStat[]};
const fmt=(n:number)=>Number(n||0).toLocaleString();
const dayKey=(date:Date)=>{const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,"0"),d=String(date.getDate()).padStart(2,"0");return `${y}-${m}-${d}`};
export default function AnalyticsPage(){const supabase=useMemo(()=>createClient(),[]),[data,setData]=useState<Analytics|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[days,setDays]=useState(30),[appFilter,setAppFilter]=useState("all"),[platformFilter,setPlatformFilter]=useState("all");
useEffect(()=>{void(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setError("Sign in to view developer analytics.");setLoading(false);return}const r=await supabase.rpc("luma_my_developer_analytics");if(r.error)setError(r.error.message);else setData(r.data as Analytics);setLoading(false)})()},[supabase]);
if(loading)return <div className="glass-page mx-auto max-w-6xl space-y-5 px-3 pb-20 sm:px-4"><div className="h-8 w-48 animate-pulse rounded bg-slate-800/70"/><div className="grid gap-4 sm:grid-cols-3">{[0,1,2].map(i=><div key={i} className="h-28 animate-pulse rounded-3xl border border-white/10 bg-slate-900/45"/>)}</div><div className="h-64 animate-pulse rounded-3xl border border-white/10 bg-slate-900/45"/></div>;
if(error||!data)return <div className="glass-page mx-auto max-w-3xl px-3 pb-20 sm:px-4"><div className="rounded-3xl border border-rose-400/20 bg-rose-500/10 p-6 text-rose-100 backdrop-blur-xl"><h1 className="text-xl font-semibold">Analytics unavailable</h1><p className="mt-2 text-sm text-rose-100/70">{error||"Analytics could not be loaded."}</p><Link href="/dashboard" className="mt-4 inline-flex text-sm font-medium text-indigo-200">← Dashboard</Link></div></div>;
const top=data.apps[0];const filteredRows=data.daily.filter(x=>(appFilter==="all"||x.app_id===appFilter)&&(platformFilter==="all"||x.platform===platformFilter));const cutoff=new Date();cutoff.setHours(0,0,0,0);cutoff.setDate(cutoff.getDate()-(days-1));const map=new Map<string,number>();filteredRows.forEach(x=>{const key=String(x.download_day).slice(0,10);if(new Date(key+"T12:00:00")>=cutoff)map.set(key,(map.get(key)||0)+Number(x.downloads))});const daily=Array.from({length:days},(_,i)=>{const date=new Date();date.setHours(12,0,0,0);date.setDate(date.getDate()-(days-1-i));const key=dayKey(date);return {download_day:key,downloads:map.get(key)||0}});const maxDaily=Math.max(1,...daily.map(x=>x.downloads));const periodTotal=daily.reduce((sum,x)=>sum+x.downloads,0);const platformOptions=Array.from(new Set(data.daily.map(x=>x.platform))).sort();
return <div className="glass-page mx-auto max-w-6xl space-y-6 px-3 pb-20 sm:px-4"><div><Link href="/dashboard" className="text-sm text-indigo-300">← Dashboard</Link><div className="relative mt-4 overflow-hidden rounded-[2rem] border border-white/10 bg-slate-900/55 p-5 shadow-2xl shadow-black/20 backdrop-blur-2xl sm:p-8"><div aria-hidden="true" className="pointer-events-none absolute -right-20 -top-24 h-64 w-64 rounded-full bg-indigo-500/15 blur-3xl"/><div className="relative"><p className="text-xs font-semibold uppercase tracking-[.16em] text-indigo-300">Private developer analytics</p><h1 className="mt-1 text-3xl font-bold text-white">Analytics</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Download activity for your published apps and clicks on your funding links. Only your developer account can access these statistics.</p></div></div></div>
<section className="glass-panel grid gap-3 p-4 sm:grid-cols-3"><select value={days} onChange={e=>setDays(Number(e.target.value))} className="glass-input"><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select><select value={appFilter} onChange={e=>setAppFilter(e.target.value)} className="glass-input"><option value="all">All apps</option>{data.apps.map(app=><option key={app.id} value={app.id}>{app.name||app.package_name||"App"}</option>)}</select><select value={platformFilter} onChange={e=>setPlatformFilter(e.target.value)} className="glass-input"><option value="all">All platforms</option>{platformOptions.map(platform=><option key={platform} value={platform}>{platform}</option>)}</select></section><div className="grid gap-4 sm:grid-cols-3"><Stat label="All-time downloads" value={fmt(data.total_downloads)}/><Stat label={`Last ${days} days`} value={fmt(periodTotal)}/><Stat label="Top app" value={top?(top.name||top.package_name||"App")+" · "+fmt(top.downloads):"—"}/></div>
<section className="rounded-3xl border border-white/10 bg-slate-900/50 p-5 shadow-lg shadow-black/10 backdrop-blur-xl sm:p-6"><div className="flex flex-wrap items-end justify-between gap-2"><div><p className="text-xs uppercase tracking-wider text-slate-500">Downloads</p><h2 className="mt-1 text-xl font-semibold text-white">Last {days} days</h2></div><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-slate-300">{fmt(periodTotal)} total</span></div><div className="mt-6 flex h-48 items-end gap-1 overflow-hidden">{daily.map((x,i)=><div key={x.download_day} title={x.download_day+" · "+x.downloads} className="group flex h-full min-w-0 flex-1 items-end"><div className="relative w-full rounded-t-md bg-indigo-500/65 transition group-hover:bg-indigo-400" style={{height:`${x.downloads?Math.max(5,x.downloads/maxDaily*100):2}%`}}>{(i===0||i===Math.floor((days-1)/2)||i===days-1)&&<span className="absolute -bottom-5 left-1/2 -translate-x-1/2 whitespace-nowrap text-[9px] text-slate-600">{x.download_day.slice(5)}</span>}</div></div>)}</div><div className="h-5"/></section>
<div className="grid gap-6 lg:grid-cols-2"><Table title="Downloads by app" rows={data.apps.map(x=>[x.name||x.package_name||"App",fmt(x.downloads)])} empty="No published apps yet."/><Table title="Downloads by platform" rows={data.platforms.map(x=>[x.platform,fmt(x.downloads)])} empty="No platform downloads yet."/></div>
<Table title="Downloads by app & platform" rows={(data.app_platforms||[]).map(x=>[(x.name||x.package_name||"App")+` · ${x.platform}`,fmt(x.downloads)])} empty="No per-platform app downloads yet."/>
<Table title="Funding link clicks" rows={data.funding.map(x=>[x.provider,fmt(x.clicks)])} empty="No funding link clicks yet."/></div>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-3xl border border-white/10 bg-slate-900/50 p-5 shadow-lg shadow-black/10 backdrop-blur-xl transition hover:-translate-y-0.5 hover:border-indigo-400/20"><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 break-words text-2xl font-bold text-white">{value}</p></div>}
function Table({title,rows,empty}:{title:string;rows:string[][];empty:string}){return <section className="rounded-3xl border border-white/10 bg-slate-900/50 p-5 shadow-lg shadow-black/10 backdrop-blur-xl sm:p-6"><h2 className="text-xl font-semibold text-white">{title}</h2>{rows.length?<div className="mt-4 divide-y divide-white/10">{rows.map((r,i)=><div key={r[0]+i} className="flex items-center justify-between gap-4 py-3 text-sm"><span className="min-w-0 truncate text-slate-300">{r[0]}</span><strong className="shrink-0 text-white">{r[1]}</strong></div>)}</div>:<div className="mt-4 rounded-2xl border border-dashed border-white/10 bg-slate-950/25 p-6 text-center text-sm text-slate-500">{empty}</div>}</section>}