"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/lib/supabase/client";
type AppStat={id:string;name:string|null;package_name:string|null;downloads:number};type PlatformStat={platform:string;downloads:number};type DailyStat={download_day:string;downloads:number};type FundingStat={provider:string;clicks:number};type Analytics={total_downloads:number;apps:AppStat[];platforms:PlatformStat[];daily:DailyStat[];funding:FundingStat[]};
const fmt=(n:number)=>Number(n||0).toLocaleString();
export default function AnalyticsPage(){const supabase=useMemo(()=>createClient(),[]),[data,setData]=useState<Analytics|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
useEffect(()=>{void(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setError("Sign in to view developer analytics.");setLoading(false);return}const r=await supabase.rpc("luma_my_developer_analytics");if(r.error)setError(r.error.message);else setData(r.data as Analytics);setLoading(false)})()},[supabase]);
if(loading)return <div className="glass-page mx-auto max-w-6xl p-8 text-slate-400">Loading analytics…</div>;if(error||!data)return <div className="glass-page mx-auto max-w-3xl p-8 text-rose-200">{error||"Analytics unavailable."}</div>;
const top=data.apps[0],maxDaily=Math.max(1,...data.daily.map(x=>Number(x.downloads)));
return <div className="glass-page mx-auto max-w-6xl space-y-6 pb-20"><div><Link href="/dashboard" className="text-sm text-indigo-300">← Dashboard</Link><p className="mt-5 text-xs font-semibold uppercase tracking-[.16em] text-indigo-300">Private developer analytics</p><h1 className="mt-1 text-3xl font-bold text-white">Analytics</h1><p className="mt-2 text-slate-400">Download activity for your published apps and clicks on your funding links.</p></div>
<div className="grid gap-4 sm:grid-cols-3"><Stat label="All-time downloads" value={fmt(data.total_downloads)}/><Stat label="Published apps" value={String(data.apps.length)}/><Stat label="Top app" value={top?(top.name||top.package_name||"App")+" · "+fmt(top.downloads):"—"}/></div>
<section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><h2 className="text-xl font-semibold text-white">Last 30 days</h2><div className="mt-5 flex h-44 items-end gap-1 overflow-x-auto">{data.daily.length?data.daily.map(x=><div key={x.download_day} title={x.download_day+" · "+x.downloads} className="flex min-w-3 flex-1 items-end"><div className="w-full rounded-t bg-indigo-500/70" style={{height:`${Math.max(4,Number(x.downloads)/maxDaily*100)}%`}}/></div>):<p className="text-sm text-slate-500">No downloads in this period.</p>}</div></section>
<div className="grid gap-6 lg:grid-cols-2"><Table title="Downloads by app" rows={data.apps.map(x=>[x.name||x.package_name||"App",fmt(x.downloads)])}/><Table title="Downloads by platform" rows={data.platforms.map(x=>[x.platform,fmt(x.downloads)])}/></div>
<Table title="Funding link clicks" rows={data.funding.length?data.funding.map(x=>[x.provider,fmt(x.clicks)]):[["No clicks yet","0"]]}/></div>}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><p className="text-xs uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-white">{value}</p></div>}
function Table({title,rows}:{title:string;rows:string[][]}){return <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6"><h2 className="text-xl font-semibold text-white">{title}</h2><div className="mt-4 divide-y divide-slate-800">{rows.map((r,i)=><div key={r[0]+i} className="flex items-center justify-between gap-4 py-3 text-sm"><span className="truncate text-slate-300">{r[0]}</span><strong className="text-white">{r[1]}</strong></div>)}</div></section>}