"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
const field="glass-input";
const cryptoOptions=[["bitcoin","Bitcoin (BTC)",["Bitcoin"]],["ethereum","Ethereum (ETH)",["Ethereum"]],["tether","Tether (USDT)",["Ethereum (ERC-20)","TRON (TRC-20)","BNB Smart Chain (BEP-20)","Solana","Polygon","Avalanche C-Chain","Arbitrum","Optimism"]],["usdc","USD Coin (USDC)",["Ethereum (ERC-20)","Solana","Base","Arbitrum","Optimism","Polygon","Avalanche C-Chain"]],["bnb","BNB",["BNB Smart Chain (BEP-20)","BNB Beacon Chain"]],["solana","Solana (SOL)",["Solana"]],["cardano","Cardano (ADA)",["Cardano"]],["dogecoin","Dogecoin (DOGE)",["Dogecoin"]],["tron","TRON (TRX)",["TRON"]],["polkadot","Polkadot (DOT)",["Polkadot"]],["avalanche","Avalanche (AVAX)",["Avalanche C-Chain","Avalanche P-Chain"]],["chainlink","Chainlink (LINK)",["Ethereum (ERC-20)","BNB Smart Chain (BEP-20)","Polygon","Arbitrum","Optimism"]],["polygon","Polygon (POL)",["Polygon","Ethereum (ERC-20)"]],["litecoin","Litecoin (LTC)",["Litecoin"]],["bitcoin_cash","Bitcoin Cash (BCH)",["Bitcoin Cash"]],["stellar","Stellar (XLM)",["Stellar"]],["monero","Monero (XMR)",["Monero"]],["toncoin","Toncoin (TON)",["TON"]],["shiba_inu","Shiba Inu (SHIB)",["Ethereum (ERC-20)","Shibarium"]] ] as const;
const cryptoKey=(currency:string,network:string)=>`${currency}::${network}`;
export default function DeveloperFundingPage(){
 const supabase=useMemo(()=>createClient(),[]); const [userId,setUserId]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null);
 const [form,setForm]=useState({donate_url:"",liberapay:"",opencollective:"",crypto_addresses:{} as Record<string,string>});
 useEffect(()=>{void (async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user){setLoading(false);return;} setUserId(user.id); const {data}=await supabase.from("luma_developer_funding").select("donate_url,liberapay,opencollective,bitcoin,litecoin,crypto_addresses").eq("developer_id",user.id).maybeSingle(); if(data)setForm({donate_url:data.donate_url||"",liberapay:data.liberapay||"",opencollective:data.opencollective||"",crypto_addresses:{...(data.crypto_addresses||{}),...(data.bitcoin&&!data.crypto_addresses?.["bitcoin::Bitcoin"]?{"bitcoin::Bitcoin":data.bitcoin}:{}),...(data.litecoin&&!data.crypto_addresses?.["litecoin::Litecoin"]?{"litecoin::Litecoin":data.litecoin}:{})}}); setLoading(false);})()},[supabase]);
 const set=(key:"donate_url"|"liberapay"|"opencollective",value:string)=>setForm(v=>({...v,[key]:value})); const setCrypto=(key:string,value:string)=>setForm(v=>({...v,crypto_addresses:{...v.crypto_addresses,[key]:value}}));
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!userId)return;setSaving(true);setMessage(null);const clean=(v:string)=>v.trim()||null;const {error}=await supabase.from("luma_developer_funding").upsert({developer_id:userId,donate_url:clean(form.donate_url),liberapay:clean(form.liberapay),opencollective:clean(form.opencollective),crypto_addresses:Object.fromEntries(Object.entries(form.crypto_addresses).map(([k,v])=>[k,v.trim()]).filter(([k,v])=>v&&!k.startsWith("xrp::"))),bitcoin:clean(form.crypto_addresses["bitcoin::Bitcoin"]||""),litecoin:clean(form.crypto_addresses["litecoin::Litecoin"]||""),updated_at:new Date().toISOString()},{onConflict:"developer_id"});setMessage(error?error.message:"Developer funding saved. These methods now apply to all your apps.");setSaving(false)};
 if(loading)return <div className="glass-page mx-auto max-w-3xl space-y-5 px-3 pb-20 sm:px-4"><div className="h-8 w-56 animate-pulse rounded bg-slate-800/70"/><div className="space-y-5 rounded-3xl border border-white/10 bg-slate-900/50 p-6 backdrop-blur-xl">{[0,1,2,3].map(i=><div key={i}><div className="mb-2 h-4 w-24 animate-pulse rounded bg-slate-800/60"/><div className="h-12 animate-pulse rounded-2xl bg-slate-800/40"/></div>)}</div></div>;
 if(!userId)return <div className="glass-page mx-auto max-w-3xl p-8 text-slate-300">Sign in to manage developer funding.</div>;
 return <div className="glass-page mx-auto max-w-3xl space-y-6 px-3 pb-20 sm:px-4"><div><Link href="/dashboard" className="text-sm text-indigo-300">← Dashboard</Link><div className="glass-panel mt-4 p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[.16em] text-indigo-300">Developer support</p><h1 className="mt-1 text-3xl font-bold text-white">Developer funding</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Configure support methods once for your developer profile. They are shown for every app you publish.</p></div></div>{message&&<div role="status" className="rounded-2xl border border-indigo-400/20 bg-indigo-500/10 p-4 text-sm text-indigo-100 backdrop-blur-xl">{message}</div>}<form onSubmit={save} className="glass-panel space-y-5 p-5 sm:p-6"><div><label className="mb-2 block text-sm text-slate-300">Donation URL</label><input type="url" value={form.donate_url} onChange={e=>set("donate_url",e.target.value)} className={field}/></div><div><label className="mb-2 block text-sm text-slate-300">Liberapay URL</label><input value={form.liberapay} onChange={e=>set("liberapay",e.target.value)} className={field}/></div><div><label className="mb-2 block text-sm text-slate-300">OpenCollective URL</label><input value={form.opencollective} onChange={e=>set("opencollective",e.target.value)} className={field}/></div><div className="border-t border-white/10 pt-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-indigo-300">Cryptocurrency</p><h2 className="mt-1 text-xl font-semibold text-white">Wallet addresses</h2><p className="mt-1 text-sm text-slate-500">Add only the currencies you accept. Leave the others empty.</p><div className="mt-4 space-y-4">{cryptoOptions.map(([currency,label,networks])=><div key={currency} className="rounded-2xl border border-white/10 bg-slate-950/25 p-4"><p className="text-sm font-semibold text-white">{label}</p><p className="mt-1 text-xs text-slate-500">{networks.length>1?"You can add addresses for multiple blockchains.":"Native network"}</p><div className="mt-3 grid gap-3 sm:grid-cols-2">{networks.map(network=>{const key=cryptoKey(currency,network);return <div key={key}><label className="mb-1.5 block text-xs text-slate-400">{network}</label><input value={form.crypto_addresses[key]||""} onChange={e=>setCrypto(key,e.target.value)} className={field} placeholder={`${label} · ${network}`}/></div>})}</div></div>)}</div></div><div className="flex flex-col-reverse gap-3 border-t border-white/10 pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-slate-500">Funding clicks can be viewed in Developer Analytics.</p><button disabled={saving} className="rounded-xl bg-indigo-500 px-5 py-2.5 font-semibold text-white transition hover:bg-indigo-400 disabled:opacity-50">{saving?"Saving…":"Save developer funding"}</button></div></form></div>
}