"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
const field="w-full rounded-xl border border-slate-700 bg-slate-950/70 px-4 py-3 text-white outline-none focus:border-indigo-500";
export default function DeveloperFundingPage(){
 const supabase=useMemo(()=>createClient(),[]); const [userId,setUserId]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null);
 const [form,setForm]=useState({donate_url:"",liberapay:"",opencollective:"",bitcoin:"",litecoin:""});
 useEffect(()=>{void (async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user){setLoading(false);return;} setUserId(user.id); const {data}=await supabase.from("luma_developer_funding").select("donate_url,liberapay,opencollective,bitcoin,litecoin").eq("developer_id",user.id).maybeSingle(); if(data)setForm({donate_url:data.donate_url||"",liberapay:data.liberapay||"",opencollective:data.opencollective||"",bitcoin:data.bitcoin||"",litecoin:data.litecoin||""}); setLoading(false);})()},[supabase]);
 const set=(key:keyof typeof form,value:string)=>setForm(v=>({...v,[key]:value}));
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!userId)return;setSaving(true);setMessage(null);const clean=(v:string)=>v.trim()||null;const {error}=await supabase.from("luma_developer_funding").upsert({developer_id:userId,donate_url:clean(form.donate_url),liberapay:clean(form.liberapay),opencollective:clean(form.opencollective),bitcoin:clean(form.bitcoin),litecoin:clean(form.litecoin),updated_at:new Date().toISOString()},{onConflict:"developer_id"});setMessage(error?error.message:"Developer funding saved. These methods now apply to all your apps.");setSaving(false)};
 if(loading)return <div className="glass-page mx-auto max-w-3xl p-8 text-slate-400">Loading funding…</div>;
 if(!userId)return <div className="glass-page mx-auto max-w-3xl p-8 text-slate-300">Sign in to manage developer funding.</div>;
 return <div className="glass-page mx-auto max-w-3xl space-y-6 pb-20"><div><Link href="/dashboard" className="text-sm text-indigo-300">← Dashboard</Link><h1 className="mt-4 text-3xl font-bold text-white">Developer funding</h1><p className="mt-2 text-slate-400">Configure support methods once for your developer profile. They are shown for every app you publish.</p></div>{message&&<div className="rounded-xl border border-slate-700 bg-slate-900/70 p-4 text-sm text-slate-200">{message}</div>}<form onSubmit={save} className="space-y-5 rounded-2xl border border-slate-800 bg-slate-900/80 p-6"><div><label className="mb-2 block text-sm text-slate-300">Donation URL</label><input type="url" value={form.donate_url} onChange={e=>set("donate_url",e.target.value)} className={field}/></div><div><label className="mb-2 block text-sm text-slate-300">Liberapay URL</label><input value={form.liberapay} onChange={e=>set("liberapay",e.target.value)} className={field}/></div><div><label className="mb-2 block text-sm text-slate-300">OpenCollective URL</label><input value={form.opencollective} onChange={e=>set("opencollective",e.target.value)} className={field}/></div><div><label className="mb-2 block text-sm text-slate-300">Bitcoin address</label><input value={form.bitcoin} onChange={e=>set("bitcoin",e.target.value)} className={field}/></div><div><label className="mb-2 block text-sm text-slate-300">Litecoin address</label><input value={form.litecoin} onChange={e=>set("litecoin",e.target.value)} className={field}/></div><button disabled={saving} className="rounded-xl bg-indigo-600 px-5 py-2.5 font-medium text-white disabled:opacity-50">{saving?"Saving…":"Save developer funding"}</button></form></div>
}