"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
const field="glass-input";
export default function DeveloperFundingPage(){
 const supabase=useMemo(()=>createClient(),[]); const [userId,setUserId]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null);
 const [form,setForm]=useState({donate_url:"",liberapay:"",opencollective:"",bitcoin:"",litecoin:""});
 useEffect(()=>{void (async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user){setLoading(false);return;} setUserId(user.id); const {data}=await supabase.from("luma_developer_funding").select("donate_url,liberapay,opencollective,bitcoin,litecoin").eq("developer_id",user.id).maybeSingle(); if(data)setForm({donate_url:data.donate_url||"",liberapay:data.liberapay||"",opencollective:data.opencollective||"",bitcoin:data.bitcoin||"",litecoin:data.litecoin||""}); setLoading(false);})()},[supabase]);
 const set=(key:keyof typeof form,value:string)=>setForm(v=>({...v,[key]:value}));
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!userId)return;setSaving(true);setMessage(null);const clean=(v:string)=>v.trim()||null;const {error}=await supabase.from("luma_developer_funding").upsert({developer_id:userId,donate_url:clean(form.donate_url),liberapay:clean(form.liberapay),opencollective:clean(form.opencollective),bitcoin:clean(form.bitcoin),litecoin:clean(form.litecoin),updated_at:new Date().toISOString()},{onConflict:"developer_id"});setMessage(error?error.message:"Developer funding saved. These methods now apply to all your apps.");setSaving(false)};
 if(loading)return <div className="glass-page mx-auto max-w-3xl space-y-5 px-3 pb-20 sm:px-4"><div className="h-8 w-56 animate-pulse rounded bg-slate-800/70"/><div className="space-y-5 rounded-3xl border border-white/10 bg-slate-900/50 p-6 backdrop-blur-xl">{[0,1,2,3].map(i=><div key={i}><div className="mb-2 h-4 w-24 animate-pulse rounded bg-slate-800/60"/><div className="h-12 animate-pulse rounded-2xl bg-slate-800/40"/></div>)}</div></div>;
 if(!userId)return <div className="glass-page mx-auto max-w-3xl p-8 text-slate-300">Sign in to manage developer funding.</div>;
 return <div className="glass-page mx-auto max-w-3xl space-y-6 px-3 pb-20 sm:px-4"><div><Link href="/dashboard" className="text-sm text-indigo-300">← Dashboard</Link><div className="glass-panel mt-4 p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-[.16em] text-indigo-300">Developer support</p><h1 className="mt-1 text-3xl font-bold text-white">Developer funding</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Configure support methods once for your developer profile. They are shown for every app you publish.</p></div></div>{message&&<div role="status" className="rounded-2xl border border-indigo-400/20 bg-indigo-500/10 p-4 text-sm text-indigo-100 backdrop-blur-xl">{message}</div>}<form onSubmit={save} className="glass-panel space-y-5 p-5 sm:p-6"><div><label className="mb-2 block text-sm text-slate-300">Donation URL</label><input type="url" value={form.donate_url} onChange={e=>set("donate_url",e.target.value)} className={field}/></div><div><label className="mb-2 block text-sm text-slate-300">Liberapay URL</label><input value={form.liberapay} onChange={e=>set("liberapay",e.target.value)} className={field}/></div><div><label className="mb-2 block text-sm text-slate-300">OpenCollective URL</label><input value={form.opencollective} onChange={e=>set("opencollective",e.target.value)} className={field}/></div><div><label className="mb-2 block text-sm text-slate-300">Bitcoin address</label><input value={form.bitcoin} onChange={e=>set("bitcoin",e.target.value)} className={field}/></div><div><label className="mb-2 block text-sm text-slate-300">Litecoin address</label><input value={form.litecoin} onChange={e=>set("litecoin",e.target.value)} className={field}/></div><div className="flex flex-col-reverse gap-3 border-t border-white/10 pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-slate-500">Funding clicks can be viewed in Developer Analytics.</p><button disabled={saving} className="rounded-xl bg-indigo-500 px-5 py-2.5 font-semibold text-white transition hover:bg-indigo-400 disabled:opacity-50">{saving?"Saving…":"Save developer funding"}</button></div></form></div>
}